### PR TITLE
Log an error if an exception occurs during logging of diffs

### LINKED ISSUE #63: No error logged if an exception occurs during the logging of differences
If, for some reason, finding differences fails no exception is logged. The `executorService` itself might fail and that would result in a error log, but anything inside the `submit` won't.

### PR DESCRIPTION
**Pull request by martinvisser**
Fixes #63

### CODE REVIEW

File: src/main/java/io/github/rabobank/shadow_tool/ShadowFlow.java [hunk 1]
```diff
@@ -170,17 +172,29 @@ public Mono<Collection<T>> compareCollections(final Mono<? extends Collection<T>
...
+        final var contextMap = MDC.getCopyOfContextMap();
+        logger.info(CALLING_NEW_FLOW, instanceNameLogPrefix, callNewFlow);
 
         if (callNewFlow) {
             try {
-                executorService.submit(() -> logDifferences(diffSupplier.get()));
-            } catch (final Exception e) {
-                logger.error("{} Failed to run the shadow flow", instanceNameLogPrefix, e);
+                executorService.submit(() -> logDifferenceWithMdc(diffSupplier, contextMap));
+            } catch (final Exception t) {
```
Comment (GuusdeWit) [inline src/main/java/io/github/rabobank/shadow_tool/ShadowFlow.java:181]: Exception t?

**Review by stevenschenk — DISMISSED** [review]

File: src/main/java/io/github/rabobank/shadow_tool/ShadowFlow.java (hunk 1 above)
Comment (martinvisser) [reply src/main/java/io/github/rabobank/shadow_tool/ShadowFlow.java:181]: Interesting, I honestly don't know where that came from. I'll change it to a more descriptive `e`.

Comment (GuusdeWit) [reply src/main/java/io/github/rabobank/shadow_tool/ShadowFlow.java]: Much better!

**Review by GuusdeWit — DISMISSED** [review]

**Review by GuusdeWit — APPROVED** [review]
